name: trainnet
channels:
    - conda-forge
    - pytorch
    - anaconda
dependencies:
    - pytorch
    - imageio
    - torchvision
    - opencv
    - scikit-learn
    - scikit-image
    - pandas
    - seaborn
    - numpy
    - matplotlib
    - scipy
    - tqdm
    - time
    - pillow
    - pip
    - pip:
        - opencv.contrib-python
   